# Generated by Django 5.2.6 on 2025-09-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(max_length=80)),
                ('is_featured', models.BooleanField(default=False)),
                ('discount', models.PositiveIntegerField(default=0, help_text='Persentase diskon (0-100). Misal 20 = 20% off')),
                ('is_limited', models.BooleanField(default=False, help_text='True kalau produk edisi terbatas')),
            ],
        ),
    ]
