# Generated by Django 5.2.6 on 2025-09-16 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Product',
        ),
    ]
