# Generated by Django 5.2.6 on 2025-09-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_news_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('shorts', 'Shorts'), ('socks', 'Socks'), ('training', 'Training Equipment'), ('bag', 'Sports Bag'), ('accessory', 'Accessory'), ('other', 'Other')], default='other', max_length=80),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
